name: Auto add NSOC'26 label to Issues

on:
  issues:
    types:
      - opened

permissions:
  issues: write
  contents: read

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Add NSOC'26 label to issue
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              labels: ["NSOC'26"],
            });